# Generated by Django 3.1 on 2020-09-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=10)),
                ('patient_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=5)),
                ('plasma', models.CharField(blank=True, max_length=5, null=True)),
                ('platelet', models.CharField(blank=True, max_length=5, null=True)),
                ('rbc', models.CharField(blank=True, max_length=5, null=True)),
                ('whole_blood', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=5)),
                ('updated_by', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='BloodStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(max_length=100)),
                ('hb', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('blood_component', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('bag', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=5)),
                ('updated_by', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='BloodTaking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plasma', models.CharField(blank=True, max_length=250, null=True)),
                ('platelet', models.CharField(blank=True, max_length=250, null=True)),
                ('rbc', models.CharField(blank=True, max_length=250, null=True)),
                ('whole_blood', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=5)),
                ('updated_by', models.CharField(max_length=5)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_bank.bloodrequest')),
            ],
        ),
    ]
