# Generated by Django 3.1 on 2020-09-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0008_auto_20200904_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='platelet',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
